# Default values for static-site.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

deploymentAnnotations: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: 
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  runAsUser: 0

service:
  type: ClusterIP
  port: 80

# ingress:
#   host: dummyapp.127.0.0.1.nip.io
#   ingressClassName: nginx
#   tlsEnabled: false
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt-staging


resources: 
  requests:
    cpu: 200m
    memory: 200Mi
  limits:
    cpu: 200m
    memory: 200Mi

nodeSelector: {}

tolerations: []

affinity: {}

# values to build and deploy static sites
updateInterval: 0 # pull and update every x seconds, set to 0 to disable - it will then only pulled+built at start of the pod
gitCloneUrl: https://github.com/gimlet-io/reactjs-test-app.git
buildImage: "node:latest"
buildScript: |
  npm install && npm run build
builtAssets: build/

# the values of initContainer onl apply if updateInterval > 0
initContainer:
  livenessProbe:
    enabled: false
    periodSeconds: 1
    failureThreshold: 10
  startupProbe:
    enabled: true
    periodSeconds: 20
    failureThreshold: 30
  readinessProbe:
    enabled: true
    periodSeconds: 20
    initialDelaySeconds: 5
  